# -*- coding: utf-8 -*-
"""Diwali Sales Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-AOKUVVtNagQUxKL-HBn6hqf3i-6LBq9
"""

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns

### import data csv file

import pandas as pd

df = pd.read_csv('Diwali Sales Data.csv',encoding = 'unicode_escape')
df.head(6)## first 10 rows

## shape  15 columns 11251 rows he
df.shape

df.info()## they give us all information

df.info()

## check null value
pd.isnull(df)

## use sum they total all null value
pd.isnull(df).sum()

##check rows and shape
df.shape

## drop null value
df.dropna(inplace = True)

## check null value drop
df.shape

##change data type
df['Amount'] = df['Amount'].astype('int')

## data type change method astype

## check data type change or not
df['Amount'].dtype

### change column name
df.rename(columns = {'Marital_Status':'Shadi'})## they din't save becaus we dint use = and inplace true

df.columns

## they give us discription
df.describe().sort_values(by = 'Amount',ascending = False)

##if we want specfic column
df[['Age','Orders','Amount']].describe()

###

"""# New Section  EXPLORATORY DATA ANALYST"""

##
df.columns

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns
a = sns.countplot(x = 'Gender',data = df)

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns
a = sns.countplot(x = 'Gender',data = df)
for bars in a.containers:## they line add values
    a.bar_label(bars)

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns

### group = gender ka
## sum amount
## value ko short kiya he amount ke basic pe ascending
df.groupby(['Gender'],as_index = False)['Amount'].sum().sort_values(by = 'Amount',ascending = False)

### this is our barplot matplotlib bala jisme x or y axix he jiske hamne name change kiye he or data hamne sales gen liya he

sales_gen   = df.groupby(['Gender'],as_index = False)['Amount'].sum().sort_values(by = 'Amount',ascending = False)
sns.barplot(x = 'Gender', y = 'Amount',data  = sales_gen)

## from above graphs we can see that most of the buyers are females and even the purchanging power of females are greater than men

"""# New Section   AGE"""

df.columns

## age ke basic pe
sns.countplot(data = df, x = 'Age Group',hue = 'Gender') ## data he df me  two axix he x and y jisme hame age group,gender columns liye he

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns
a  = sns.countplot(data = df, x = 'Age Group',hue = 'Gender')## they retuen plot with value using for loop
for bars in a.containers:
    a.bar_label(bars)

## total amount of age group
sales_age = df.groupby(['Age Group'],as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Age Group' , y = 'Amount', data = sales_age)

## from above graph we can see that most of the buyers are of age group between 26 - 35 yrs famale

### state
df.columns

## state
sales_age = df.groupby(['State'],as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False).head(10)

## total  orders kitne he state ke basic pe
sales_age = df.groupby(['State'],as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False).head(10)
sns.barplot(x = 'State' , y = 'Orders', data = sales_age)## bar plot banaye he
sns.set(rc = {'figure.figsize':(25,10)})## yeh line space create krti he nm me x axis pe chart size

## State wise Total Amount

## total  amount  kitne he state ke basic pe
sales_state = df.groupby(['State'],as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.barplot(x = 'State' , y = 'Amount', data = sales_state)## bar plot banaye he
sns.set(rc = {'figure.figsize':(25,10)})## yeh line space create krti he nm me x axis pe chart size

# above graphs we can see that unexpectedly most of the orders are from uttar pradesh ,maharastra and karnatak but total sales amolunt is from up ,karnataka and then maharastra

## maritual stuts ke baisc pe data nikalana
a = sns.countplot(data = df , x = 'Marital_Status')
sns.set(rc = {'figure.figsize':(2,3)})
for bars in a.containers:
    a.bar_label(bars)

### amount ke basic pe marital stusts
sales_state= df.groupby(['Marital_Status','Gender'],as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.barplot(data = sales_state,x = 'Marital_Status' , y = 'Amount',hue = 'Gender')## bar plot banaye he
sns.set(rc = {'figure.figsize':(25,5)})## yeh line space create krti he nm me x axis pe chart size

### OCCUPATION
sns.set(rc = {'figure.figsize': (20,5)})
a = sns.countplot(data = df ,x = 'Occupation')
for bars in a.containers:
    a.bar_label(bars)

# from above graph we can see the most buyer are working in it sector

df.columns

### PRODUCT CATEGOREY

sns.set(rc = {'figure.figsize': (30,5)})## differen product category he jisme sabse jada salse ko batati he
a = sns.countplot(data = df ,x = 'Product_Category')
for bars in a.containers:
    a.bar_label(bars)

### PRODUCT CATEGORY KE BASIC PE GROUP BY AMOUNT USE KIYA HE

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns
sales_state = df.groupby(['Product_Category'],as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.barplot(x = 'Product_Category' , y = 'Amount', data = sales_state)## bar plot banaye he
sns.set(rc = {'figure.figsize':(25,10)})## yeh line space create krti he nm me x axis pe chart size

## THIS GRAPHS WE CLEARLY SEE THAT MOST O THE SOLD PRODUCTS AR FOOD,CLOTHING ,AND ELECTRONIES

### TOP SALING PRODUCT
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import seaborn as sns
sales_state = df.groupby(['Product_ID'],as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False).head(10)
sns.barplot(x = 'Product_ID' , y = 'Orders', data = sales_state)## bar plot banaye he
sns.set(rc = {'figure.figsize':(20,12)})## yeh line space create krti he nm me x axis pe chart size

"""# New Section    CONCLUSION WOMEN ARE GROUP 26- 35 YRS FROM UP,MAHARASTRA AND KARNATAKA WORKING IN IT ,HEALTHCARE AND AVITATION ARE MOST LIKELY BUY PRODUCTS FROM FOOD,CLOTHING AND ELECTRONIS....."""